name: msc-scrp-1
channels:
  - conda-forge
  - defaults
dependencies:
  - aom=3.9.1
  - bzip2=1.0.8
  - ca-certificates=2025.11.12
  - cairo=1.18.4
  - dav1d=1.2.1
  - ffmpeg=8.0.1
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freetype=2.14.1
  - fribidi=1.0.16
  - gdk-pixbuf=2.44.4
  - glslang=16.1.0
  - graphite2=1.3.14
  - harfbuzz=12.3.0
  - icu=78.1
  - lame=3.100
  - lerc=4.0.0
  - libdeflate=1.25
  - libexpat=2.7.3
  - libffi=3.5.2
  - libfreetype=2.14.1
  - libfreetype6=2.14.1
  - libglib=2.86.3
  - libiconv=1.18
  - libintl=0.22.5
  - libjpeg-turbo=3.1.2
  - liblzma=5.8.1
  - libogg=1.3.5
  - libopus=1.6
  - libpng=1.6.53
  - librsvg=2.60.0
  - libsqlite=3.51.1
  - libtiff=4.7.1
  - libusb=1.0.29
  - libvorbis=1.3.7
  - libvulkan-loader=1.4.328.1
  - libxml2=2.15.1
  - libxml2-16=2.15.1
  - libzlib=1.3.1
  - openh264=2.6.0
  - openssl=3.6.0
  - pango=1.56.4
  - pcre2=10.47
  - pip=25.3
  - pixman=0.46.4
  - python=3.11.14
  - sdl2=2.32.56
  - sdl3=3.2.30
  - setuptools=80.9.0
  - shaderc=2025.5
  - spirv-tools=2025.4
  - svt-av1=3.1.2
  - tk=8.6.13
  - tzdata=2025c
  - ucrt=10.0.26100.0
  - vc=14.3
  - vc14_runtime=14.44.35208
  - vcomp14=14.44.35208
  - vs2015_runtime=14.44.35208
  - wheel=0.45.1
  - x264=1!164.3095
  - x265=3.5
  - zstd=1.5.7
  - pip:
      - annotated-types==0.7.0
      - anyio==3.7.1
      - beautifulsoup4==4.14.3
      - certifi==2025.11.12
      - charset-normalizer==3.4.4
      - click==8.3.1
      - colorama==0.4.6
      - dacite==1.9.2
      - deprecated==1.3.1
      - fastapi==0.103.2
      - h11==0.16.0
      - idna==3.11
      - jaconv==0.4.1
      - markdown-it-py==4.0.0
      - mdurl==0.1.2
      - mutagen==1.47.0
      - pillow==12.1.0
      - platformdirs==4.5.1
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - pygments==2.19.2
      - pykakasi==2.3.0
      - python-dateutil==2.9.0.post0
      - python-slugify==8.0.4
      - pytube==15.0.0
      - rapidfuzz==3.14.3
      - redis==7.1.0
      - requests==2.32.5
      - rich==13.9.4
      - six==1.17.0
      - sniffio==1.3.1
      - soundcloud-v2==1.6.0
      - soupsieve==2.8.1
      - spotdl==4.4.3
      - spotipy==2.25.2
      - starlette==0.27.0
      - syncedlyrics==1.0.1
      - text-unidecode==1.3
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - unidecode==1.4.0
      - urllib3==2.6.2
      - uvicorn==0.23.2
      - websockets==14.2
      - wrapt==2.0.1
      - yt-dlp==2025.12.8
      - ytmusicapi==1.11.4
prefix: C:\Users\U1\miniconda3\envs\msc-scrp-1
